### ISSUE TITLE
User changeable clear frequency

### ISSUE THREAD

**Issue by tjsreece** [sindresorhus/clear-downloads#1]
There should be an option to change how often the Downloads are auto-cleared, not a forced 10 secondes.

**Comment by sindresorhus** [comment]
Why?

**Comment by tjsreece** [comment]
Why not?

**Comment by SamVerschueren** [comment]
@tjsreece With the `Why?` question, Sindre asks why you need it. What's the added value of this feature? What's your use case? You can bloat every library with loads of features, but why do that if they aren't going to be used. So to ask the question again, what's wrong with the default 10 seconds?

**Comment by tjsreece** [comment]
Nothing is wrong with what the timer is set to. However I just felt that it would provide a better user expereince if they were allowed to change the timer in which the downloads were cleared. Also personally I would like to see it done too.

**Comment by sindresorhus** [comment]
Nah, just bloat for no apparent gain.
