### ISSUE TITLE
Interrupted Downloads are Cleared

### ISSUE THREAD

**Issue by nikolayarhangelov** [sindresorhus/clear-downloads#3]
I was doing a large download and my network got disconnected for a moment. Chrome showed a Retry option in the Downloads page, but the download got cleared.

Expected result - I should be able to Retry failed downloads.

**Comment by sindresorhus** [comment]
Chrome unfortunately doesn't expose any way for us to remove downloads based on status. It's either all downloads or based on a time range.

https://developer.chrome.com/extensions/browsingData#type-RemovalOptions

You should send them a feature request.
