### ISSUE TITLE
Extension no longer available on Chrome Web Store

### ISSUE THREAD

**Issue by imtbl** [sindresorhus/clear-downloads#4]
I've just set up a new computer and noticed that my Chrome sync didn't automatically install this extension.

When trying to go the [extension page in the Chrome Web Store](https://chrome.google.com/webstore/detail/clear-downloads/bknoejjhcfmakcibhifepfkegpjdnadk) it just responds with a 404 page.

**Comment by Ismael-GT** [comment]
I have the same problem

**Comment by sindresorhus** [comment]
Google automatically took it down  because it didn't have a screenshot.

I've added a screenshot now, so we'll wait and see:

<img width="604" alt="screen shot 2018-09-24 at 17 14 27" src="https://user-images.githubusercontent.com/170270/45947155-6a038400-c01d-11e8-801a-982b5e289458.png">

**Comment by imtbl** [comment]
Looks like adding a screenshot worked and it's available again. Thanks! :)
